[project]
name = "nanochat-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.2.0",
    "modal>=1.2.0",
    "regex>=2025.11.3",
    "tiktoken>=0.12.0",
]
